<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="19661" started-at="2022-02-09T17:02:54Z" finished-at="2022-02-09T17:03:13Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="19661" started-at="2022-02-09T17:02:54Z" finished-at="2022-02-09T17:03:13Z">
      <class name="Week4.LoginTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Week4.LoginTest@27efef64]" name="beforeMethod" is-config="true" duration-ms="7450" started-at="2022-02-09T17:02:54Z" finished-at="2022-02-09T17:03:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="logincheck()[pri:0, instance:Week4.LoginTest@27efef64]" name="logincheck" duration-ms="1708" started-at="2022-02-09T17:03:01Z" finished-at="2022-02-09T17:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Week4.LoginTest@27efef64]" name="afterMethod" is-config="true" duration-ms="0" started-at="2022-02-09T17:03:03Z" finished-at="2022-02-09T17:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Week4.LoginTest@27efef64]" name="beforeMethod" is-config="true" duration-ms="9089" started-at="2022-02-09T17:03:03Z" finished-at="2022-02-09T17:03:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="logincheck1()[pri:0, instance:Week4.LoginTest@27efef64]" name="logincheck1" duration-ms="1378" started-at="2022-02-09T17:03:12Z" finished-at="2022-02-09T17:03:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Week4.LoginTest.logincheck1(LoginTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Week4.LoginTest@27efef64]" name="afterMethod" is-config="true" duration-ms="1" started-at="2022-02-09T17:03:13Z" finished-at="2022-02-09T17:03:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Week4.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
